Simplified Chinese translation
Luligabi1/NoIndium pull request #2
Opened 2022-04-23 07:06 UTC by pkstDev

Quick Chinese translation

2022-04-25 23:14 UTC, Luligabi1 requested changes
```
  "header.noindium.indium": "警告: 客户端未找到铟",
  "message.noindium.indium": "警告: 在你的游戏客户端中存在的一个或多个模组可能会因为使用没有安装铟的钠而产生问题，从轻微的视觉错误到游戏崩溃不等。建议点击以下一个按钮下载铟以避免这些问题：",
```

Please don't translate "Indium" and "Sodium" literally to chinese, as that might confuse players to where the buttons are leading them to.

2022-04-29 04:13 UTC, pkstDev commented
ah my bad
fixed

2022-04-29 19:16 UTC, Luligabi1 approved these changes

2022-04-29 19:17 UTC, Luligabi1 commented
> ah my bad fixed

No problem, it's just a small thing to make sure this mod can do its purpose on any language 🙂 I'll release a new version with your translation soon

2022-04-29 19:18 UTC, merged